name: Node
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: yarn install
        run: |
          node --version
          yarn install --immutable --immutable-cache --check-cache
        env:
          CI: true
          FORCE_COLOR: 1

      - name: Eslint
        run: yarn eslint .
      - name: Validate package setup
        run: |
          yarn setup
          yarn prettier --write .
          git diff --exit-code -- . :^.yarn
      - name: Typescript
        run: yarn lerna run tsc
      - name: Test packages
        run: yarn vitest --run --coverage
      - name: Integration tests
        run: yarn node --test integration/

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
